spring:
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/reactor_netdisk
    username: reactor_netdisk
    password: pWMR7nnEW2zcicKJ
server:
  ssl:
    key-store-password: 5ki1t7c077
    key-store-type: JKS
    key-store: classpath:vps.dluserver.cn.jks


logging:
  level:
    root: WARN


file:
  upload:
    path: /root/reactor-netdisk/upload