spring:
  sql:
    init:
      mode: never
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/reactor_netdisk_test
    username: reactor_netdisk_test
    password: jKdH38Js2S72CykW

logging:
  level:
    root: INFO


file:
  upload:
    path: D:\\Temp
#    path: /Users/monody/Desktop/netdisk